### ISSUE TITLE
CAAPF Investigate possible usage of new label `cluster-api.cattle.io/disable-fleet-auto-import` usable by fleet

### ISSUE THREAD

**Issue by thehejik** [rancher/rancher-turtles-e2e#101]
from turtles/pull/1004:
```
Cluster or namespace may specify `cluster-api.cattle.io/disable-fleet-auto-import` label to exclude it from automatic import process with fleet.
```

Maybe we can somehow prevent installing the second fleet agent by rancher?

**Comment by thehejik** [comment]
In our turtles-e2e we are currently using this `fleet-addon-config` patch:
```
const patch = { 
  data: { 
    manifests: { 
      isNestedIn: true, // This is just a helper for parsing of nested data
      spec: { 
        cluster: { 
          hostNetwork: true, 
          selector: { 
            matchLabels: { cni: 'by-fleet-addon-kindnet' } 
          } 
        } 
      } 
    } 
  } 
};

```
* As you can notice bellow the `hostNetwork: true` is already present in default `fleet-addon-config` so it is redundant
* New label `cluster-api.cattle.io/disable-fleet-auto-import` has the opposite effect compared to our custom label `cni: 'by-fleet-addon-kindnet'` from the patch.
   * Clusters with the `disable-fleet-auto-import` label will not install the fleet-agent via fleet-addon.
   * Whereas our custom label `cni: 'by-fleet-addon-kindnet'` ensures that only the cluster(s) with this label gets the fleet-agent installed.
   * Keeping our current label selector avoids the need to add `disable-fleet-auto-import` to every cluster not meant to use the fleet-addon.


For now, I propose keeping our patch with the custom label `cni: 'by-fleet-addon-kindnet'` to ensure only the targeted cluster gets the `fleet-agent` via fleet-addon. We should also remove `hostNetwork: true` from our patch since it's already configured by default.

This is default `fleet-addon-config` configmap (helm template) from current turtles:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: fleet-addon-config
  namespace: '{{ .Values.rancherTurtles.namespace }}'
  annotations:
    "helm.sh/hook": "post-install, post-upgrade"
    "helm.sh/hook-weight": "2"
data:
  manifests: |-
    apiVersion: addons.cluster.x-k8s.io/v1alpha1
    kind: FleetAddonConfig
    metadata:
      name: fleet-addon-config
    spec:
      clusterClass:
        patchResource: true
        setOwnerReferences: true
      cluster:
        patchResource: true
        setOwnerReferences: true
        hostNetwork: true
        selector:
          matchLabels:
            cluster-api.cattle.io/rancher-auto-import: "true"
          matchExpressions:
            - key: cluster-api.cattle.io/disable-fleet-auto-import
              operator: DoesNotExist
        namespaceSelector:
          matchLabels:
            cluster-api.cattle.io/rancher-auto-import: "true"
          matchExpressions:
            - key: cluster-api.cattle.io/disable-fleet-auto-import
              operator: DoesNotExist
```
