### ISSUE TITLE
ui e2e: Create CAPA EC2 Kubeadm cluster from Clusterclass

### ISSUE THREAD

**Issue by cpinjani** [rancher/rancher-turtles-e2e#114]
Add coverage for cluster creation using clusterclass using create cluster wizard for CAPA Kubeadm
(CAPI UI Extension: v0.8.2)

Template:
```
apiVersion: cluster.x-k8s.io/v1beta1
kind: ClusterClass
metadata:
  name: quick-start
spec:
  controlPlane:
    ref:
      apiVersion: controlplane.cluster.x-k8s.io/v1beta1
      kind: KubeadmControlPlaneTemplate
      name: quick-start-control-plane
    machineInfrastructure:
      ref:
        kind: AWSMachineTemplate
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
        name: quick-start-control-plane
  infrastructure:
    ref:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
      kind: AWSClusterTemplate
      name: quick-start
  workers:
    machineDeployments:
      - class: default-worker
        template:
          bootstrap:
            ref:
              apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
              kind: KubeadmConfigTemplate
              name: quick-start-worker-bootstraptemplate
          infrastructure:
            ref:
              apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
              kind: AWSMachineTemplate
              name: quick-start-worker-machinetemplate
  variables:
    - name: region
      required: true
      schema:
        openAPIV3Schema:
          type: string
          default: us-east-1
    - name: sshKeyName
      required: true
      schema:
        openAPIV3Schema:
          type: string
          default: default
    - name: controlPlaneMachineType
      required: true
      schema:
        openAPIV3Schema:
          type: string
          default: t3.large
    - name: workerMachineType
      required: true
      schema:
        openAPIV3Schema:
          type: string
          default: t3.large
  patches:
    - name: region
      definitions:
        - selector:
            apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
            kind: AWSClusterTemplate
            matchResources:
              infrastructureCluster: true
          jsonPatches:
            - op: add
              path: /spec/template/spec/region
              valueFrom:
                variable: region
    - name: sshKeyName
      definitions:
        - selector:
            apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
            kind: AWSClusterTemplate
            matchResources:
              infrastructureCluster: true
          jsonPatches:
            - op: add
              path: /spec/template/spec/sshKeyName
              valueFrom:
                variable: sshKeyName
        - selector:
            apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
            kind: AWSMachineTemplate
            matchResources:
              controlPlane: true
              machineDeploymentClass:
                names:
                  - default-worker
          jsonPatches:
            - op: add
              path: /spec/template/spec/sshKeyName
              valueFrom:
                variable: sshKeyName
    - name: controlPlaneMachineType
      definitions:
        - selector:
            apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
            kind: AWSMachineTemplate
            matchResources:
              controlPlane: true
          jsonPatches:
            - op: replace
              path: /spec/template/spec/instanceType
              valueFrom:
                variable: controlPlaneMachineType
    - name: workerMachineType
      definitions:
        - selector:
            apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
            kind: AWSMachineTemplate
            matchResources:
              machineDeploymentClass:
                names:
                  - default-worker
          jsonPatches:
            - op: replace
              path: /spec/template/spec/instanceType
              valueFrom:
                variable: workerMachineType
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSClusterTemplate
metadata:
  name: quick-start
spec:
  template:
    spec: { }
---
kind: KubeadmControlPlaneTemplate
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
metadata:
  name: quick-start-control-plane
spec:
  template:
    spec:
      kubeadmConfigSpec:
        clusterConfiguration:
          apiServer:
            extraArgs:
              cloud-provider: aws
          controllerManager:
            extraArgs:
              cloud-provider: aws
        initConfiguration:
          nodeRegistration:
            name: '{{ ds.meta_data.local_hostname }}'
            kubeletExtraArgs:
              cloud-provider: aws
        joinConfiguration:
          nodeRegistration:
            name: '{{ ds.meta_data.local_hostname }}'
            kubeletExtraArgs:
              cloud-provider: aws
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSMachineTemplate
metadata:
  name: quick-start-control-plane
spec:
  template:
    spec:
      # instanceType is a required field (OpenAPI schema).
      instanceType: REPLACEME
      iamInstanceProfile: "control-plane.cluster-api-provider-aws.sigs.k8s.io"
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSMachineTemplate
metadata:
  name: quick-start-worker-machinetemplate
spec:
  template:
    spec:
      # instanceType is a required field (OpenAPI schema).
      instanceType: REPLACEME
      iamInstanceProfile: "nodes.cluster-api-provider-aws.sigs.k8s.io"
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: "quick-start-worker-bootstraptemplate"
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          name: '{{ ds.meta_data.local_hostname }}'
          kubeletExtraArgs:
            cloud-provider: aws
---
apiVersion: v1
data: ${CNI_RESOURCES}
kind: ConfigMap
metadata:
  name: cni-${CLUSTER_NAME}-crs-0
---
apiVersion: addons.cluster.x-k8s.io/v1beta1
kind: ClusterResourceSet
metadata:
  name: ${CLUSTER_NAME}-crs-0
spec:
  clusterSelector:
    matchLabels:
      cni: ${CLUSTER_NAME}-crs-0
  resources:
  - kind: ConfigMap
    name: cni-${CLUSTER_NAME}-crs-0
  strategy: ApplyOnce
```

**Comment by valaparthvi** [comment]
Can I pick it up? If no one has started working on it already.

**Comment by cpinjani** [comment]
Yes, sure.

**Comment by thehejik** [comment]
So far the template doesn't work, the control plane is provisioned in EC2 but capi is not aware of that, probably some problem with public address/lb assignment. Alex is trying to find a solution.

I was able to provision EC2 cp node by using `eu-west-2` and k8s `v1.31.0`.

```
./clusterawsadm ami list --region eu-west-2
KUBERNETES VERSION   REGION      OS               NAME                                         AMI ID
v1.31.4              eu-west-2   flatcar-stable   capa-ami-flatcar-stable-v1.31.4-1738227358   ami-0801411d94cec38ea
v1.31.0              eu-west-2   ubuntu-24.04     capa-ami-ubuntu-24.04-v1.31.0-1739348996     ami-0988c3c36e3080c43
v1.31.0              eu-west-2   ubuntu-22.04     capa-ami-ubuntu-22.04-v1.31.0-1739347184     ami-0219a26b88f5ecaea
v1.31.0              eu-west-2   flatcar-stable   capa-ami-flatcar-stable-v1.31.0-1739350445   ami-03d8cd831818713e4
v1.30.8              eu-west-2   ubuntu-24.04     capa-ami-ubuntu-24.04-v1.30.8-1739360448     ami-0347524f9096fe64b
v1.30.8              eu-west-2   ubuntu-22.04     capa-ami-ubuntu-22.04-v1.30.8-1739359056     ami-0965c055e01cd1137
v1.30.8              eu-west-2   flatcar-stable   capa-ami-flatcar-stable-v1.30.8-1739361876   ami-0061a0f53414ae037
v1.30.5              eu-west-2   ubuntu-24.04     capa-ami-ubuntu-24.04-v1.30.5-1728924607     ami-0054630107ba40e56
v1.30.5              eu-west-2   ubuntu-22.04     capa-ami-ubuntu-22.04-v1.30.5-1728920688     ami-0475c7d6a764f9da0
v1.30.5              eu-west-2   flatcar-stable   capa-ami-flatcar-stable-v1.30.5-1728926211   ami-0e78ef01acf76afcd
v1.30.2              eu-west-2   ubuntu-24.04     capa-ami-ubuntu-24.04-v1.30.2-1729082892     ami-0f7ea581bce570c29
v1.30.2              eu-west-2   ubuntu-22.04     capa-ami-ubuntu-22.04-v1.30.2-1729078952     ami-00b5d7ac893cff88e
v1.30.2              eu-west-2   flatcar-stable   capa-ami-flatcar-stable-v1.30.2-1729094390   ami-014fcfd35ed499224
v1.29.9              eu-west-2   ubuntu-24.04     capa-ami-ubuntu-24.04-v1.29.9-1728670729     ami-0d17e33dceaa14223
v1.29.9              eu-west-2   ubuntu-22.04     capa-ami-ubuntu-22.04-v1.29.9-1728669184     ami-092d69975bd73f105
v1.29.9              eu-west-2   flatcar-stable   capa-ami-flatcar-stable-v1.29.9-1728672309   ami-0d73b630387749dba
v1.29.8              eu-west-2   ubuntu-24.04     capa-ami-ubuntu-24.04-v1.29.8-1729074685     ami-06cd081d94b7aa904
v1.29.8              eu-west-2   ubuntu-22.04     capa-ami-ubuntu-22.04-v1.29.8-1729071846     ami-0388152b7ad78bd35
v1.29.8              eu-west-2   flatcar-stable   capa-ami-flatcar-stable-v1.29.8-1729076396   ami-049632201d41ba063
v1.29.7              eu-west-2   ubuntu-24.04     capa-ami-ubuntu-24.04-v1.29.7-1729177869     ami-0d2bc0665f855215c
v1.29.7              eu-west-2   ubuntu-22.04     capa-ami-ubuntu-22.04-v1.29.7-1729176322     ami-0f7546f61a58904f8
v1.29.7              eu-west-2   flatcar-stable   capa-ami-flatcar-stable-v1.29.7-1729181280   ami-0b13d7bc052b18475
```

**Comment by thehejik** [comment]
I was able to apply this and provisioned a cluster but there were some problems:
* fleet-agent pod stuck in pending state because there was a taint on a cp node - I could remove the taint by: `kubectl taint nodes ip-10-0-154-141.eu-west-2.compute.internal node-role.kubernetes.io/control-plane-` and then the pod started
* I was trying calico cni but for some reason it didnt work - not all pods were running - probably related to the taints
* needs more investigation
* I was able to get kubeconfig by `clusterctl get kubeconfig th-capa > th-capa.yaml`
* there are some problems with aws cleanup - when I follow the ui wizard to create a cluster then not all resources are getting deleted
* when the cluster is defined together in clusterclass resource as shown below then the cleanup works
```
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  labels:
    cni: calico
    ccm: external
    csi: external
  name: th-capa
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
  topology:
    class: turtles
    controlPlane:
      replicas: 1
    variables:
    - name: region
      value: eu-west-2
    - name: sshKeyName
      value: thehejik
    - name: controlPlaneMachineType
      value: t3.medium
    - name: workerMachineType
      value: t3.medium
    version: v1.31.0
    workers:
      machineDeployments:
      - class: default-worker
        name: md-0
        replicas: 1
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: ClusterClass
metadata:
  name: turtles
  namespace: default
spec:
  controlPlane:
    ref:
      apiVersion: controlplane.cluster.x-k8s.io/v1beta1
      kind: KubeadmControlPlaneTemplate
      name: turtles-control-plane
    machineInfrastructure:
      ref:
        kind: AWSMachineTemplate
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
        name: turtles-control-plane
  infrastructure:
    ref:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
      kind: AWSClusterTemplate
      name: turtles
  workers:
    machineDeployments:
      - class: default-worker
        template:
          bootstrap:
            ref:
              apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
              kind: KubeadmConfigTemplate
              name: turtles-worker-bootstraptemplate
          infrastructure:
            ref:
              apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
              kind: AWSMachineTemplate
              name: turtles-worker-machinetemplate
  variables:
    - name: region
      required: true
      schema:
        openAPIV3Schema:
          type: string
          default: us-east-1
    - name: sshKeyName
      required: true
      schema:
        openAPIV3Schema:
          type: string
          default: default
    - name: controlPlaneMachineType
      required: true
      schema:
        openAPIV3Schema:
          type: string
          default: t3.large
    - name: workerMachineType
      required: true
      schema:
        openAPIV3Schema:
          type: string
          default: t3.large
  patches:
    - name: region
      definitions:
        - selector:
            apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
            kind: AWSClusterTemplate
            matchResources:
              infrastructureCluster: true
          jsonPatches:
            - op: add
              path: /spec/template/spec/region
              valueFrom:
                variable: region
    - name: sshKeyName
      definitions:
        - selector:
            apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
            kind: AWSClusterTemplate
            matchResources:
              infrastructureCluster: true
          jsonPatches:
            - op: add
              path: /spec/template/spec/sshKeyName
              valueFrom:
                variable: sshKeyName
        - selector:
            apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
            kind: AWSMachineTemplate
            matchResources:
              controlPlane: true
              machineDeploymentClass:
                names:
                  - default-worker
          jsonPatches:
            - op: add
              path: /spec/template/spec/sshKeyName
              valueFrom:
                variable: sshKeyName
    - name: controlPlaneMachineType
      definitions:
        - selector:
            apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
            kind: AWSMachineTemplate
            matchResources:
              controlPlane: true
          jsonPatches:
            - op: replace
              path: /spec/template/spec/instanceType
              valueFrom:
                variable: controlPlaneMachineType
    - name: workerMachineType
      definitions:
        - selector:
            apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
            kind: AWSMachineTemplate
            matchResources:
              machineDeploymentClass:
                names:
                  - default-worker
          jsonPatches:
            - op: replace
              path: /spec/template/spec/instanceType
              valueFrom:
                variable: workerMachineType
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSClusterTemplate
metadata:
  name: turtles
  namespace: default
spec:
  template:
    spec:
      controlPlaneLoadBalancer:
        loadBalancerType: nlb
        healthCheckProtocol: HTTPS
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlaneTemplate
metadata:
  name: turtles-control-plane
  namespace: default
spec:
  template:
    spec:
      kubeadmConfigSpec:
        clusterConfiguration:
          apiServer:
            extraArgs:
              cloud-provider: external
          controllerManager:
            extraArgs:
              cloud-provider: external
        initConfiguration:
          nodeRegistration:
            kubeletExtraArgs:
              cloud-provider: external
            name: '{{ ds.meta_data.local_hostname }}'
        joinConfiguration:
          nodeRegistration:
            kubeletExtraArgs:
              cloud-provider: external
            name: '{{ ds.meta_data.local_hostname }}'
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSMachineTemplate
metadata:
  name: turtles-control-plane
  namespace: default
spec:
  template:
    spec:
      # instanceType is a required field (OpenAPI schema).
      instanceType: t3.medium
      iamInstanceProfile: "control-plane.cluster-api-provider-aws.sigs.k8s.io"
      rootVolume:
        size: 50
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSMachineTemplate
metadata:
  name: turtles-worker-machinetemplate
  namespace: default
spec:
  template:
    spec:
      # instanceType is a required field (OpenAPI schema).
      instanceType: t3.medium
      iamInstanceProfile: "nodes.cluster-api-provider-aws.sigs.k8s.io"
      rootVolume:
        size: 50
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: "turtles-worker-bootstraptemplate"
  namespace: default
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            cloud-provider: external
          name: '{{ ds.meta_data.local_hostname }}'
---
apiVersion: addons.cluster.x-k8s.io/v1beta1
kind: ClusterResourceSet
metadata:
  name: crs-cni
  namespace: default
spec:
  clusterSelector:
    matchLabels:
      cni: calico
  resources:
  - kind: ConfigMap
    name: calico-cni
  strategy: ApplyOnce
---
apiVersion: addons.cluster.x-k8s.io/v1beta1
kind: ClusterResourceSet
metadata:
  name: crs-ccm
  namespace: default
spec:
  clusterSelector:
    matchLabels:
      ccm: external
  resources:
  - kind: ConfigMap
    name: cloud-controller-manager-addon
  strategy: ApplyOnce
---
apiVersion: addons.cluster.x-k8s.io/v1beta1
kind: ClusterResourceSet
metadata:
  name: crs-csi
  namespace: default
spec:
  clusterSelector:
    matchLabels:
      csi: external
  resources:
  - kind: ConfigMap
    name: aws-ebs-csi-driver-addon
  strategy: ApplyOnce
```
