### ISSUE TITLE
ui e2e: Create CAPZ cluster from Clusterclass

### ISSUE THREAD

**Issue by cpinjani** [rancher/rancher-turtles-e2e#115]
Add coverage for cluster creation using clusterclass using create cluster wizard for CAPZ AKS
(CAPI UI Extension: v0.8.2)

Template:
```
apiVersion: cluster.x-k8s.io/v1beta1
kind: ClusterClass
metadata:
  name: ${CLUSTER_CLASS_NAME}
  namespace: default
spec:
  controlPlane:
    ref:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: AzureManagedControlPlaneTemplate
      name: ${CLUSTER_NAME}-control-plane
  infrastructure:
    ref:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: AzureManagedClusterTemplate
      name: ${CLUSTER_NAME}
  workers:
    machinePools:
    - class: default-system
      template:
        bootstrap:
          ref:
            apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
            kind: RKE2ConfigTemplate
            name: ${CLUSTER_NAME}-pool0
        infrastructure:
          ref:
            apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
            kind: AzureManagedMachinePoolTemplate
            name: ${CLUSTER_NAME}-pool0
    - class: default-worker
      template:
        bootstrap:
          ref:
            apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
            kind: RKE2ConfigTemplate
            name: ${CLUSTER_NAME}-pool1
        infrastructure:
          ref:
            apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
            kind: AzureManagedMachinePoolTemplate
            name: ${CLUSTER_NAME}-pool1
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureManagedControlPlaneTemplate
metadata:
  name: ${CLUSTER_NAME}-control-plane
  namespace: default
spec:
  template:
    spec:
      identityRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: AzureClusterIdentity
        name: cluster-identity
      location: southcentralus
      resourceGroupName: "${CLUSTER_NAME}"
      subscriptionID: ${AZURE_SUBSCRIPTION_ID}
      version: ${KUBERNETES_VERSION}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureManagedClusterTemplate
metadata:
  name: ${CLUSTER_NAME}
  namespace: default
spec:
  template:
    spec: {}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureManagedMachinePoolTemplate
metadata:
  name: ${CLUSTER_NAME}-pool0
  namespace: default
spec:
  template:
    spec:
      mode: System
      name: pool0
      sku: Standard_D2s_v3
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureManagedMachinePoolTemplate
metadata:
  name: ${CLUSTER_NAME}-pool1
  namespace: default
spec:
  template:
    spec:
      mode: User
      name: pool1
      sku: Standard_D2s_v3
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: RKE2ConfigTemplate
metadata:
  name: ${CLUSTER_NAME}-pool0
  namespace: default
spec:
  template:
    spec: {}
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: RKE2ConfigTemplate
metadata:
  name: ${CLUSTER_NAME}-pool1
  namespace: default
spec:
  template:
    spec: {}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureClusterIdentity
metadata:
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    clusterctl.cluster.x-k8s.io/move-hierarchy: "true"
  name: cluster-identity
  namespace: default
spec:
  allowedNamespaces: {}
  clientID: ${AZURE_CLIENT_ID}
  clientSecret:
    name: cluster-identity-secret
    namespace: default
  tenantID: ${AZURE_TENANT_ID}
  type: ServicePrincipal
```
